name: "Rustlings Progress Updater"
description: "Updates your README with your current Rustlings exercise and progress table"
author: "soda3x"
branding:
  icon: check-square
  color: red
inputs: {}
runs:
  using: "composite"
  steps:
    - name: Fix permissions on script
      shell: bash
      run: chmod +x entrypoint.sh
    - name: Run README updater script
      shell: bash
      run: ./entrypoint.sh